### PR TITLE
reworked prefferences, leaderboard

### PR DESCRIPTION
**Pull request by SashaBondarchuk**

### CODE REVIEW

**Comment by SashaBondarchuk** [comment]
[[IMPROVEMENT#35] [Preferenses block] The elements must be in one vertical line](https://trello.com/c/YqJi9Urs/292-improvement35-preferenses-block-the-elements-must-be-in-one-vertical-line)

**Comment by SashaBondarchuk** [comment]
[[IMPROVEMENT#34] [Code fight] Сode Fight only with friends](https://trello.com/c/9IVlC3wM/291-improvement34-code-fight-%D1%81ode-fight-only-with-friends)

**Comment by SashaBondarchuk** [comment]
[[BUG#124] [Edit profile page] The block with the preferencies](https://trello.com/c/3DlA1jbP/276-bug124-edit-profile-page-the-block-with-the-preferencies)

**Comment by SashaBondarchuk** [comment]
image

image

image

image

**Review by Limbo2332 — APPROVED** [review]

**Review by apofis96 — APPROVED** [review]

**Pull request merged**
