### PR TITLE
reworked styles, created btn component

### PR DESCRIPTION
**Pull request by SashaBondarchuk**
image

image

image

## HOVER: 
image
image

### CODE REVIEW

**Comment by SashaBondarchuk** [comment]
[[IMPROVEMENT#] [26] Change button style](https://trello.com/c/RJoDBzKx/267-improvement-26-change-button-style)

**Comment by SashaBondarchuk** [comment]
[[BUG#133] [Sign Up|Sign in] Redirects the user to the landing page after registration or sing in through Google account](https://trello.com/c/4dJXPzUI/286-bug133-sign-upsign-in-redirects-the-user-to-the-landing-page-after-registration-or-sing-in-through-google-account)

**Review by tatianahutii — APPROVED** [review]

**Review by Limbo2332 — APPROVED** [review]

**Comment by SashaBondarchuk** [comment]
[[IMPROVEMENT#34] [Code fight] Сode Fight only with friends](https://trello.com/c/9IVlC3wM/291-improvement)

**Comment by SashaBondarchuk** [comment]
[[BUG#124] [Edit profile page] The block with the preferencies](https://trello.com/c/3DlA1jbP/276-bug124-edit-profile-page-the-block-with-the-preferencies)

**Comment by SashaBondarchuk** [comment]
[[IMPROVEMENT#35] [Preferenses block] The elements must be in one vertical line](https://trello.com/c/YqJi9Urs/292-improvement35-preferenses-block)

**Comment by SashaBondarchuk** [comment]
image

image

image

image

**Pull request merged**
