### PR TITLE
Feature/46 full main page

### PR DESCRIPTION
**Pull request by pashamed**
https://trello.com/c/l9FGPK0h/46-full-main-page

localhost_4200_main(iPad Mini)
localhost_4200_main(iPhone SE)
localhost_4200_main(Surface Pro 7)

### CODE REVIEW

**Comment by pashamed** [comment]
[Full main page](https://trello.com/c/l9FGPK0h/46-full-main-page)

**Comment by pashamed** [comment]
[Full main page](https://trello.com/c/l9FGPK0h/46-full-main-page)

**Comment by pashamed** [comment]
[Full main page](https://trello.com/c/l9FGPK0h/46-full-main-page)

**Comment by pashamed** [comment]
[Full main page](https://trello.com/c/l9FGPK0h/46-full-main-page)

**Review by tatianahutii — APPROVED** [review]

**Review by apofis96 — APPROVED** [review]

**Pull request merged**
